### PR TITLE
Change Icon stories

### PR DESCRIPTION
**Pull request by mcslayer**
## Done
- Update the vanilla-framework dependency to version 4.18.0.
- Update the sass dependency to version 1.79.4 (aligning with the version used by the vanilla-framework). This update addresses compatibility issues with the new Sass syntax. See details https://github.com/canonical/vanilla-framework/pull/5370.
- Implement enhancements for Icon stories:
  - Add all icons from vanilla-framework to constants
  - Enable icon selection for Base and Social sections
  - Add a Standard story allowing icon selection
  - Add an Additional story with options for icon selection and descriptions
  - Add a story that includes all available icons for use
- Add select for theme changing 

I hope these improvements will prove beneficial.

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### QA steps

- Steps for QA.

### Percy steps

- List any expected visual change in Percy, or write something like "No visual changes expected" if none is expected.

## Fixes

Fixes: # .

### CODE REVIEW

**Comment by mcslayer** [comment]
I realize that I probably should have split this PR into three separate ones:
- Package updates
- Icon stories
- Theme selector
If it makes the code review more convenient for you, I can separate them.

**Comment by bartaz** [comment]
This is nice, thanks @mcslayer. You are touching on couple areas here, and I guess it could be worth to separate them a bit for easier review and QA (and being able to merge some quicker without blocking on questions/decisions in others).

I think I see separation into 3 PRs here:
- Vanilla update to latest version (with sass)
- Theming support for stories
- Icons updates

Would it be OK for you to separate this like that?

**Comment by mcslayer** [comment]
Ok, let's do it step by step

**Comment by bartaz** [comment]
Thanks. And for some reason I haven't seen your comment where you suggested practically exactly the same yourself before :)

**Pull request closed without merging**
