### PR TITLE
feat: add application layout components

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Add Vanilla application layout components.

Note: this PR requires the follow to land first:
- https://github.com/canonical/react-components/pull/1088
- https://github.com/canonical/react-components/pull/1089

Original PR and discussion: https://github.com/canonical/react-components/pull/1031.

A number of tests were performed using these components:

https://github.com/canonical/lxd-ui/pull/768
https://github.com/canonical/identity-platform-admin-ui/pull/309
https://github.com/canonical/maas-ui/pull/5434
https://github.com/canonical/juju-dashboard/pull/1752
https://github.com/canonical/rebac-admin/pull/106
https://github.com/canonical/anbox-cloud-dashboard/pull/806

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### QA steps

Note: the following PRs need to merge before this can be QAed:
- https://github.com/canonical/react-components/pull/1088
- https://github.com/canonical/react-components/pull/1089
- 
- Go to the demo storybook.
- Go to the application layout components and check the docs look OK.

### Percy steps

- New components expected.

## Fixes

Fixes: #420.

### CODE REVIEW

**Comment by huwshimi** [comment]
This will fail CI until the following PRs land:
- https://github.com/canonical/react-components/pull/1088
- https://github.com/canonical/react-components/pull/1089

**Comment by edlerd** [comment]
The other PRs landed, and this one was rebased on main. There is a type confusion in the `AppNavigation.stories.tsx` file. I am not sure how to resolve or why it doesn't automatically pick up the right type with the icon prop. @huwshimi can you please have a look at this.

**Comment by huwshimi** [comment]
> The other PRs landed, and this one was rebased on main. There is a type confusion in the `AppNavigation.stories.tsx` file. I am not sure how to resolve or why it doesn't automatically pick up the right type with the icon prop. @huwshimi can you please have a look at this.

Fixed!

**Review by edlerd — COMMENTED** [review]
The "Default" view in storybook for AppNavigation, AppStatus, AppAside and others are empty. Should we change those?

**Comment by huwshimi** [comment]
> The "Default" view in storybook for AppNavigation, AppStatus, AppAside and others are empty. Should we change those?

Fixed! I merged these with stories that had content.

**Review by edlerd — APPROVED** [review]
LGTM

**Pull request merged**
