### PR TITLE
feat(ContextualMenu): allow node label

### PR DESCRIPTION
**Pull request by petermakowski**
## Done

- allow passing a node for ContextualMenu toggleLabel

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### QA steps

- Steps for QA.

## Fixes

Fixes: # .

### CODE REVIEW

**Review by ndv99 — APPROVED** [review]
Nice one, been needing this for a while. We should put this on notifs as well

**Comment by petermakowski** [comment]
> Nice one, been needing this for a while. We should put this on notifs as well

@ndv99 Feel free to open a PR for it!

**Comment by petermakowski** [comment]
> @petermakowski What's the context for this? It opens up adding **any** HTML elements into the button, and we don't want that. Label is supposed to be just a text.

It allows for more flexibility (e.g. adding an icon in front of text like in the example below).
image

**Comment by bartaz** [comment]
> It allows for more flexibility (e.g. adding an icon in front of text like in the example below).
> image

OK. Not sure if contextual menu was designed and developed to cover such use case (from visual, functional, accessibility, etc. points of view). But I guess it's fine to keep it if that works for you.

I'm just a bit worried that this technically allows to put anything in there, regardless of being an icon/checkbox, regardless of contents of menu items.

Strictly speaking I would argue that this is a separate "ticked" variant of a contextual menu, that has these checkboxes built in, and doesn't allow users to put just anything in there.

But as I said, let's keep it for now, we can always restrict it more if it becomes misused.

**Pull request merged**
