### PR TITLE
fix(List): fix stepped list dom validation error for nested paragraphs

### PR DESCRIPTION
**Pull request by shdq**
## Description of the changes

Hello there! I hope you're doing great!

This PR is intended to fix DOM validation error for the stepped `List` with nested paragraphs.

**Related issues**: #875 #789 

Wrapper HTML element for the content of an item from `<p>` to `<div>`.

**Before changes**

```html
<ol class="p-stepped-list">
    <li class="p-stepped-list__item">
        <h3 class="p-stepped-list__title">Title and content as string</h3>
        <p class="p-stepped-list__content">Content as string</p>
    </li>
</ol>
```

**After changes**

```html
<ol class="p-stepped-list">
    <li class="p-stepped-list__item">
        <h3 class="p-stepped-list__title">Title and content as string</h3>
        <div class="p-stepped-list__content">Content as string</div>
    </li>
</ol>
```

After the change, when you provide one or several paragraphs as `content` it won't be an issue.

```typescript

const items = [
    {
        title: "With two paragraphs of text",
        content: (
            <>
              <p>Paragraph 1</p>
              <p>Paragraph 2</p>
            </>
        ),
    }
];

```

## QA

Unit tests were added for this case, and they pass with no regression on other tests. Linted the code and tests (I would suggest adding a pre-push hook for linting, because there are plenty of warnings in other components).

I checked the storybook: stepped `List` rendered correctly. Packed as a local package, installed in an empty Vite project: it also worked well.

Should I also add a story with this use case to the storybook?

If you have any questions, I would be happy to answer!

**Outside of the scope of this PR**

- I [issued](https://github.com/canonical/vanilla-framework/issues/4656) a bug in `vanilla framework`, that is connected to the stepped `List`.
- There is a problem with the types for `List` items, for the stepped list. Items prop always has the type `ListItem[]`, but supposed to be `SteppedListItem[]`. If you want I can create an issue and we can continue the conversation there.

### CODE REVIEW

**Comment by shdq** [comment]
Hey there! 

The workflow failed because of a bug in the types for the list component.

Basically, if you have `stepped={true}` property it should be `SteppedListItem[]` type for items, and `ListItem[]` overwise.

Another problem with types is that `title` prop should be omitted from HTML attributes because there is a global `title` attribute and they are conflicting.

I created all the possible variants for items for the stepped list:

```typescript
const items: SteppedListItem[] = [
    { title: "Title and content as string", content: "Content as string" },
    { title: "With content as paragraph", content: <p>Paragraph</p> },
    {
      title: (
        <>
          With&nbsp;<strong>bold text</strong>&nbsp;and text
        </>
      ),
      content: (
        <>
          <p>Paragraph 1</p>
          <p>Paragraph 2</p>
        </>
      ),
    },
    {
      // title and content as numbers
      title: 1234567890,
      content: 1234567890,
    },
    {
      title: "With custom class name",
      content: '"my-class" added to <li>',
      className: "my-class",
    },
    {
      title: "With title as <h2>",
      content: "Item with changes title element",
      titleElement: "h2",
    },
  ];
```

But also there is an option "Stepped without headings" in [docs](https://vanillaframework.io/docs/patterns/lists#vertical-stepped) that is not supported by types: `title` is a required property in `SteppedListItem`.

I mentioned this problem above, and I wrote a fix for this.

@ClementChaumel  I want to hear your thoughts on this.

**Comment by ClementChaumel** [comment]
Hey @shdq !

What you've done so far looks good! If you can fix the type error and maybe rename the item title to something less ambiguous I think we're looking at a closed issue.

Please do push your changes and when the tests pass I'll give it another review.

Thank you very much for the time and thoughts you put into this!

**Review by ClementChaumel — APPROVED** [review]
Great stuff!

**Comment by ClementChaumel** [comment]
Thank you for your work on this issue and the detail you went into explaining your reasoning! That's a resounding :+1: !! :)

**Pull request merged**
