### PR TITLE
docs(storybook): Theming support for stories

### PR DESCRIPTION
**Pull request by mcslayer**
## Done

- Hide default background select
- Add global theme select Light/Dark/Paper for strorybook
- Add HOC decorator for all stories
- Add special hack for docs background

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### QA steps

- Steps for QA.

### Percy steps

- List any expected visual change in Percy, or write something like "No visual changes expected" if none is expected.

## Fixes

Fixes: # .

### CODE REVIEW

**Comment by bartaz** [comment]
Demo: https://react-components-1151.demos.haus/

**Comment by bartaz** [comment]
This is awesome addition @mcslayer!

We have a requirement for all PRs to be up to date with main branch, so please rebase now that your Vanilla update is merged, thx!

**Comment by bartaz** [comment]
Is there some kind of storybook documentation or recommendation that you followed when adding the theme switcher?

**Comment by mcslayer** [comment]
There is no ready-made special documentation for this. The code is based on personal experience of using storybook in projects

**Comment by mcslayer** [comment]
I made the order in the commits and made 1 commit with a force push.

Regarding the title: everything is primitive there. You can use the abstract "Theme", or take the title from the options. So I changed the titles everywhere in the list to `Theme: Light`, `Theme: Dark`,` Theme: Paper`

**Comment by mcslayer** [comment]
If you apply this global control, I'm preparing something else :)

ezgif-7-2bdfc4dc2e

**Review by bartaz — APPROVED** [review]
Great addition, thank you!

**Pull request merged**
