### PR TITLE
Extend Button to ActionButton

### PR DESCRIPTION
**Pull request by carkod**
## Done

Extend Button to ActionButton

### Storybook

Check rendered `ActionButton` https://react-components-589.demos.haus/?path=/story/actionbutton--default-story

## Fixes

Fixes: https://github.com/canonical-web-and-design/react-components/issues/189

### CODE REVIEW

**Comment by hatched** [comment]
I understand this is still a WIP but can you create an issue which explains why you're making this change and attach it to this PR plz.

**Comment by hatched** [comment]
You can ignore my previous comment, I totally missed the link 😆

**Comment by carkod** [comment]
> You can ignore my previous comment, I totally missed the link

Yeah sorry, Cristina just connected the issue

**Comment by carkod** [comment]
The `ActionButton` is using refs to get the width and height of the element, and this is not working because we need to forwardRef to the `Button` parent component, but the `forwardRef` is not working with the custom type, and I am not sure how to add this to the type template or maybe it can't be added.

**Comment by bartaz** [comment]
@Caleb-Ellis @huwshimi Carlos started working on this, and we also just noticed a comment in code:

https://github.com/canonical-web-and-design/react-components/blob/81315bd8a74799ad62030c2933cf8f86df953330/src/components/ActionButton/ActionButton.tsx#L119-L122

Does this mean this issue is blocked? Can `Button` component be updated in a way that will allow using `forwardRef` with it?

**Comment by Caleb-Ellis** [comment]
It seems like there are some options for using generics with `forwardRef` e.g. https://fettblog.eu/typescript-react-generic-forward-refs/. I'd wait for @huwshimi's response though since he did the `ActionButton` TypeScript conversion and might have some more insight.

My two cents are to leave this for now - I imagine it'll be quite a large structural change to get this to work (maybe not in terms of LOC but in terms of our approach to generics in react-components).

**Comment by carkod** [comment]
> It seems like there are some options for using generics with `forwardRef` e.g. https://fettblog.eu/typescript-react-generic-forward-refs/. I'd wait for @huwshimi's response though since he did the `ActionButton` TypeScript conversion and might have some more insight.
> 
> My two cents are to leave this for now - I imagine it'll be quite a large structural change to get this to work (maybe not in terms of LOC but in terms of our approach to generics in react-components).
> 
> EDIT: Sorry, I should say - don't feel the need to get this done, but if you can come up with a nice solution I'd be happy to see it merged. :) Basically, the PR should solve the following:
> 
> 1. Have `ActionButton` props be a strict superset of `Button` props, including the generic `P`.
> 2. Be able to pass a `ref` from `ActionButton` down to `Button` while still maintaining the type safety when using `P`.

Oh that was the first article I read when I was trying to add `forwardRef` to `Button`. But in the article they suggest:
```
const Button = React.forwardRef((props, ref) => (
  <button type="button" {...props} ref={ref}>
    {props.children}
  </button>
));
```
Which in our case I can't do:

sea-of-red

Not sure, I suppose the custom generic type (`export type Props<P = null>..`) needs to be extended or changed somehow?

**Comment by hatched** [comment]
Sometimes it's worth taking a step back and re-evaluating the complexity of the feature. 
  - Should `Button` ever be anything other than a `button`? 
  - Is the generic necessary?

Often times it's not worth over complicating one component when two would do just fine.

**Comment by Caleb-Ellis** [comment]
> Sometimes it's worth taking a step back and re-evaluating the complexity of the feature.
> 
> * Should `Button` ever be anything other than a `button`?
> * Is the generic necessary?
> 
> Often times it's not worth over complicating one component when two would do just fine.

I was strongly considering removing the generic as well, but stopped short of recommending it. In MAAS there is literally only one place where we use Button as an anchor tag, and we don’t even use a generic there for type-safety.

Still, I think there is some use for Button to be dynamic like that. But I can’t imagine any instance in which we want ActionButton to not be a button, so it might actually make sense for them to be entirely separate components. Maybe we could just split out the common props and share those?

**Comment by bartaz** [comment]
> Still, I think there is some use for Button to be dynamic like that. But I can’t imagine any instance in which we want ActionButton to not be a button, so it might actually make sense for them to be entirely separate components. Maybe we could just split out the common props and share those?

Yes, I guess the main purpose behind making ActionButton reuse the button is to make sure they share the same props. Namely - ActionButton should allow all the styling available on the Button (all the color variants, dense, small, whatnot). The problem is that if we keep them separate, anytime we change something in Vanilla button we need to remember to change it in two separate places.

**Comment by huwshimi** [comment]
I think the Button was made to take a generic so that we could support navigation events with a Button. For instance the ContextualMenu component can [take a generic for the button](https://github.com/canonical-web-and-design/react-components/blob/master/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx#L14) so that we can pass [react-router Link components](https://reactrouter.com/web/api/Link).

As far as adding a ref to the Button goes I'd be tempted to use a custom ref prop e.g. `innerRef` or something, like the [second option](https://fettblog.eu/typescript-react-generic-forward-refs/#option-2%3A-create-a-custom-ref-%2F-the-wrapper-component) in the article linked to above. While this introduces a non-standard prop for refs it is easy to work with and does not require significant changes to the Button component. That prop can also be easily deprecated in the future if a built-in way of handling generics ever becomes available.

**Comment by huwshimi** [comment]
Just to add to this because I happened to see the same pattern in use in Formik today, they use the `innerRef` pattern for their components: https://formik.org/docs/api/field#innerref.

**Comment by ClementChaumel** [comment]
Hey @carkod and maybe @huwshimi Do you have any context on this?
Is this still relevant, should it be investigated or should we just close it? Thanks!

**Comment by carkod** [comment]
> #189

Well, I guess the context is this https://github.com/canonical/react-components/issues/189. But if it's not required anymore, then I guess we can close it

**Pull request closed without merging**
