### PR TITLE
ci: Add GitHub action to upload TICS report to TIOBE

### PR DESCRIPTION
**Pull request by bartaz**
## Done

- Added GH action workflow to run test coverage and upload TICS report to TIOBE

## QA

- Verify that the [test run](https://github.com/canonical/react-components/actions/runs/9108936123/job/25040738406?pr=1087) of this action succeeded 
- You can ignore that the CI job is listed as failed in CI checks on PR

### CODE REVIEW

**Review by jmuzina — APPROVED** [review]
Looks good, nice work :)

**Comment by huwshimi** [comment]
I'm curious if you investigated using their GitHub Action: https://github.com/tiobe/tics-github-action#tics-github-action for this or does it not work for our needs?

**Comment by bartaz** [comment]
@huwshimi interesting find. No, I did not. I was following setup instructions I got from TIOBE and previous work @edlerd did for Anbox.

@edlerd Did you try the GH action?

**Comment by edlerd** [comment]
> @huwshimi interesting find. No, I did not. I was following setup instructions I got from TIOBE and previous work @edlerd did for Anbox.
> 
> @edlerd Did you try the GH action?

I tested the GitHub action, when setting up tiobe for lxd-ui. It failed to succeed. As the local run with the bare commands succeeded, I decided to keep them in the workflow going forward.

**Pull request merged**
